### PR TITLE
Adjusting SN g4 and NDK gen VD fhicls

### PR DESCRIPTION
**Pull request by lpaulucc**
KeepEMShowerDaughters set to true for supernova fhicls
Change in the generator name in NDK+BKG gen fhicls to be the same as NDK signal only

### CODE REVIEW

**Comment by calcuttj** [comment]
Is this ready to be merged?

**Comment by lpaulucc** [comment]
Although shower daughters tracking is enabled in HD, Dom asked not to have it as default in VD, not even for LE events. So I have updated the PR.

**Comment by calcuttj** [comment]
Ok. Please let me know when it's ready to be merged and I'll get it in this week's release

**Comment by absolution1** [comment]
> Although shower daughters tracking is enabled in HD, Dom asked not to have it as default in VD, not even for LE events. So I have updated the PR.

Hi @lpaulucc 
Sorry I think I may have caused confusion before.  It's fine to keep the flagg enabled in the VD LE fcl so that it is the same as in HD.  
What I was saying before was that, in my opinion, keeping the children should be disabled in all of the fcls unless it's very well motivated to keep them.

**Comment by calcuttj** [comment]
What's the status of this?

**Comment by lpaulucc** [comment]
Since the only major change is actually on the NDK fhicls (and I was postponing it for a while), I think it can be merged. I will take a look at the FlashMatchModule to see if I can fix the rollup issue directly there.

**Pull request merged**
