### PR TITLE
VD fhicls for Marley sim in larger geo

### PR DESCRIPTION
**Pull request by lpaulucc**

### CODE REVIEW

**Comment by lpaulucc** [comment]
New fhicls needed for evaluation of low energy events in the Vertical Drift using the larger geometry (1x8x14): At g4 stage, use of LE physics list; for anatree, setting input from Marley to extract MC Truth information. Also, including a missing CMakelist in the gen/background folder and including this folder in the gen CMakelist.

**Review by absolution1 — COMMENTED** [review]
Hi @lpaulucc 

Generally looks good.
I think the anatree fcl could inherit from `standard_anatree_dunevd10kt_1x8x6_3view.fcl`.  That way you'd only need to override the services and the needed params for anatree to look at the Marley data products.

**Comment by lpaulucc** [comment]
Thanks for the suggestion, @absolution1. I have changed the fhicl accordingly.

**Review by absolution1 — APPROVED** [review]
Looks great.  Thanks for modifying the fcl!

**Pull request merged**
