### PR TITLE
Radiological modules of protodune-vd simulation update

### PR DESCRIPTION
**Pull request by szhang17phys**
For radiological modules of `dunesw/fcl/protodunevd/gen_protodunevd_radio.fcl` and `dunesw/fcl/protodunevd/[gen_protodunevd_cosmics_radio.fcl`, they are updated from @local::protodunesp_** to @local::protodunevd_**. Updates for @local::protodunevd_** also happen at dunesim repo.

### CODE REVIEW

**Comment by YoannKermaidic** [comment]
Looks good to me.

**Comment by szhang17phys** [comment]
Fhicl for protoDUNE-HD fast optical simulation based on computable graph module method added.

**Comment by YoannKermaidic** [comment]
Hi @szhang17phys ,
Can this be also used for PDVD out of the box or adapted to PDVD?

**Comment by jroto** [comment]
I don't think the workflow is right. I'm working in updating these fhcils, please wait before merging.

**Comment by YoannKermaidic** [comment]
Got it. I'll wait for your green lights ;-)

**Comment by jroto** [comment]
I've just added a new PR with a better workflow for PDHD. I would suggest to remove the fhicl from this PR.
Also, I would not add the Rn generator for the PDVD geometry, since Rn applies underground.

**Comment by YoannKermaidic** [comment]
Hi,
Regarding the radiologicals, I have a PhD student that looks into the low energy part of the PD spectrum.
Therefore any radiological component is interesting to him. If that does not take too much CPUs and memory, I would keep the Rn222 - but maybe that component has very low rate and is irrelevant (I suspect that it was needed for PDSP if it is there, isn't it?)

**Comment by jroto** [comment]
I'm pretty sure they included it by mistake, just extrapolating from the FD.
The rate number is actually just a TDR requirement.
However, this generator is very old. I would suggest to use the new decay0 generator. Why we are not copying those?
https://github.com/DUNE/dunesim/blob/86d14bcf97b6169099f1c8d832a8e68f3a69383f/dunesim/EventGenerator/Radiological/dune_radiological_model_decay0.fcl#L14
Also, since the new generator just takes the volume name as an input, we don't need a fhicl table for PDVD, we can directly use the same from the far detector.

**Comment by YoannKermaidic** [comment]
Shall we get inspiration from here:
https://github.com/DUNE/dunesim/blob/develop/dunesim/EventGenerator/Radiological/prodbackground_radiological_decay0_v3_5_dune10kt_1x2x2.fcl
-> I presume the activities should be properly re-calculated based on GDML file volumes.

**Comment by jroto** [comment]
Yes they are, because they take the volume tag, and this depends on the geometry. It is the same thing for the energy deposits.

So I think we can add directly to the fhicl:
`
      Ar39GenInLAr:             @local::dune10kt_39Ar_in_LAr
      Kr85GenInLAr:             @local::dune10kt_85Kr_in_LAr
      Ar42GenInLAr:             @local::dune10kt_42Ar_in_LAr
      K42From42ArGenInLAr:      @local::dune10kt_42Kfrom42Ar_in_LAr`

**Pull request merged**
