### PR TITLE
Adjustments needed for the LE MC production

### PR DESCRIPTION
**Pull request by lpaulucc**
Several adjustments in fhicls for the LE production. This PR is connected to the following PRs:
- https://github.com/DUNE/duneopdet/pull/35
- https://github.com/DUNE/dunesim/pull/42
- https://github.com/DUNE/dunecore/pull/80
(SHOULD NOT BE MERGED BEFORE THE PRs ABOVE)

### CODE REVIEW

**Comment by calcuttj** [comment]
trigger build with DUNE/duneopdet#35 DUNE/dunecore#80 DUNE/dunesim#42

**Comment by calcuttj** [comment]
trigger build with DUNE/duneopdet#35 DUNE/dunecore#80 DUNE/dunesim#42

**Comment by calcuttj** [comment]
trigger build with DUNE/duneopdet#35 DUNE/dunecore#80 DUNE/dunesim#42

**Comment by Li-Jiaoyang97** [comment]
Hi @lpaulucc, do we also need a supernova g4 fhicl for stage 2 as well, similar as [supernova_g4stage1_dunevd10kt_1x8x14_3view_30deg.fcl](https://github.com/DUNE/dunesw/pull/71#diff-93df67282849a36fc1002e9969220673694668e3edfaf0466787a86787bfa6ee) that you created? Thanks!

**Comment by lpaulucc** [comment]
Hi @Li-Jiaoyang97 , thanks for taking a look. I don't think we need a supernova stage 2. The difference in the standard and supernova fhicl is in the physics list geant4 uses for simulating the propagation of particles. Since stage 2 only has the xenon fast optical sim and it uses the IonAndScint object created in stage 1, it should be fine to only have a standard stage 2.

**Review by calcuttj — APPROVED** [review]

**Pull request merged**
