### PR TITLE
Create prodgenie_atmnu_max_weighted_dune10kt_1x2x6.fcl

### PR DESCRIPTION
**Pull request by pgranger23**
Creates a fcl file to be used for the atmospherics sample production by the HEP WG.
Has been tested locally to generate small samples.

Depends on https://github.com/DUNE/dunesim/pull/46 to be merged.

### CODE REVIEW

**Comment by absolution1** [comment]
Hi @pgranger23 
Thank you for this PR, and thank you for updating the name.
The configuration looks OK but I don't think the job fcl (the one that you run with `lar -c`) is the appropriate place to define all of these overrides.  It would keep with the style if these overrides were moved into an appropriate upstream configuration fcl.

It looks like the upstream fcls that you're inheriting from pull the genie atmospheric params from here: https://github.com/DUNE/dunesim/blob/develop/dunesim/EventGenerator/GENIE/genie_dune.fcl#L277

So, two questions for you:
 - How many of the overrides that you're defining in prodgenie_atmnu_max_weighted_dune10kt_1x2x6.fcl could be collected into the dune_fd_genie_atmo_max_flux parameter set in genie_dune.fcl?
 - Which fcl parameters make the simulation 'weighted' ?

**Comment by pgranger23** [comment]
Hi @absolution1, and thanks for your answer.
Typically, the part of the config that makes the simulation "weighted" is the following:
```
# Using the power spectrum weighted generation
physics.producers.generator.GenFlavors: [-14, 14, 12, -12, 16, -16]
physics.producers.generator.FluxType: "atmo_POWER"
physics.producers.generator.SpectralIndex: 2.5
physics.producers.generator.AtmoEmin: 0.1 
physics.producers.generator.AtmoEmax: 100 
physics.producers.generator.ForceApplyFlxWgt: true

physics.producers.generator.FluxSearchPaths: "/cvmfs/dune.osgstorage.org/pnfs/fnal.gov/usr/dune/persistent/stash/TaskForce_Flux/atmos/Honda_interp/"                                                        
physics.producers.generator.FluxFiles: [
    "honda_2d_homestake_2015_numu.root",
    "honda_2d_homestake_2015_numu.root",
    "honda_2d_homestake_2015_numu.root",
    "honda_2d_homestake_2015_numu.root",
    "honda_2d_homestake_2015_numu.root",
    "honda_2d_homestake_2015_numu.root"
    ] #Using nu_mu flux as a baseline to weight all the events.
```

that I could move to `genie_dune.fcl` under a new `dune_fd_genie_atmo_max_weighted_honda` config. I would prefer to keep the previous config untouched to still make it available to people.
Then I don't know if the flux rotation and AV cut should also be moved upstream in an additional config such as `dune_fd_genie_atmo_max_weighted_honda_rot_AV` or rather kept in this job fcl.

Do you have an opinion on this?

**Comment by absolution1** [comment]
Hi @pgranger23 
OK so it looks like most of the config defines the weighted part.
So, I think the entire config could be moved into a dedicated parameter set in genie_dune.fcl

It would probably be a good idea to run a fcl dump now `lar -c  prodgenie_atmnu_max_weighted_dune10kt_1x2x6.fcl --debug-config fcldump.txt` before making any changes.  Then run another fcl dump after moving the parameter set.  This should ensure that the parsed fcl remains the same.

**Comment by pgranger23** [comment]
Thanks a lot for the feedback.
So I opened a PR on dunesim to move things in `genie_dune.fcl` -> https://github.com/DUNE/dunesim/pull/46
I think this PR can be left in standby waiting for a dunesim release to be made, including this dunesim PR, so that I can make adequate modifications here.

**Comment by absolution1** [comment]
No problem.  If you update the main text for the pull request to say that this PR depends on the dunesim pr then the merging can be coordinated to happen at the same time.

**Review by tomjunk — APPROVED** [review]
Approved, and merged  dunesim PR 46 before doing so.

**Pull request merged**
